#!/bin/bash
#
# Wrapper script for josm
#

if [[ ${JOSM_HOME} ]]; then
  opt="-Djosm.home=${JOSM_HOME}"
else
  opt="-Djosm.dir.name=JOSM"
fi

java -Xmx1536m $opt -jar /usr/lib/josm/josm-tested.jar "$@"
